import * as THREE from "three";
import { OrbitControls } from "./vendor/OrbitControls.js";
const BF=window.BlueFox3D,library=BF?.ObjectLibrary;
if(!library)throw new Error("CUO exécutable introuvable : BlueFox3D.ObjectLibrary.");
const canvas=document.querySelector("#viewport");
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x06111b);scene.fog=new THREE.Fog(0x06111b,80,155);
const camera=new THREE.PerspectiveCamera(48,1,.1,240);camera.position.set(0,78,130);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=6;controls.maxDistance=210;controls.maxPolarAngle=Math.PI*.48;controls.rotateSpeed=1.35;controls.panSpeed=1.6;controls.zoomSpeed=1.05;controls.screenSpacePanning=true;controls.zoomToCursor=true;controls.mouseButtons.LEFT=null;controls.mouseButtons.RIGHT=THREE.MOUSE.ROTATE;controls.mouseButtons.MIDDLE=THREE.MOUSE.DOLLY;
scene.add(new THREE.HemisphereLight(0xbcecff,0x172016,2.4));const sun=new THREE.DirectionalLight(0xffffff,4.2);sun.position.set(-22,42,24);sun.castShadow=true;scene.add(sun);
const PLATFORM=Object.freeze({width:96,depth:100,y:.3}),CENTERS=Object.freeze({showroom:-48,sandbox:48}),platforms=[];
function makePlatform(name,x,color){const root=new THREE.Group(),slab=new THREE.Mesh(new THREE.BoxGeometry(PLATFORM.width,.6,PLATFORM.depth),new THREE.MeshStandardMaterial({color,roughness:.88}));slab.position.set(x,0,0);slab.receiveShadow=true;slab.userData.platform=name;root.add(slab);const grid=new THREE.GridHelper(PLATFORM.width,20,0x3a7584,0x21404c);grid.position.set(x,PLATFORM.y+.012,0);root.add(grid);const label=BF.makeLabel(THREE,name==="showroom"?"CATALOGUE CUO · XL → S":"PLATEAU TEST · GLISSER / DÉPOSER");label.position.set(x,1.25,-PLATFORM.depth/2+1.2);label.scale.set(9.5,1.75,1);root.add(label);scene.add(root);platforms.push(slab);return slab}
const showroomPlatform=makePlatform("showroom",CENTERS.showroom,0x243a42),sandboxPlatform=makePlatform("sandbox",CENTERS.sandbox,0x263c35);
const palette={accent:0x66e4ff,ground:0x405664,sky:0x071724,vegetation:0x63c991,mineral:0x8bcce7,ruin:0x72808d},catalog=library.list({status:"active"}),validation=library.validate(),rank={XL:0,L:1,M:2,S:3};catalog.sort((a,b)=>(rank[a.size]??9)-(rank[b.size]??9)||a.label.localeCompare(b.label,"fr"));
const roots=[];let id=1,selected=null,selectionVisual=null,moveMode=false,drag=null,pointerDown=null,cameraTransition=null,toastTimer=null;const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
function toast(message){const node=document.querySelector("#toast");node.textContent=message;node.classList.add("visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("visible"),3200)}
function ground(root){const box=new THREE.Box3().setFromObject(root);if(Number.isFinite(box.min.y))root.position.y+=PLATFORM.y-box.min.y}
function create(type,position,origin="sandbox",variant=0){const instance=library.create(THREE,type,palette,variant),root=instance.root;root.position.copy(position);root.userData.labId=id++;root.userData.labOrigin=origin;root.userData.labInstance=instance;root.userData.labVariant=variant;ground(root);root.userData.labInitialTransform={position:root.position.clone(),rotation:root.rotation.clone()};scene.add(root);roots.push(root);return root}
function populate(){const columns=5,xStep=18,zStep=16,startX=CENTERS.showroom-(columns-1)*xStep/2,rows=Math.ceil(catalog.length/columns),startZ=-(rows-1)*zStep/2+1;catalog.forEach((d,i)=>{const root=create(d.type,new THREE.Vector3(startX+i%columns*xStep,PLATFORM.y,startZ+Math.floor(i/columns)*zStep),"showroom",i%3),label=BF.makeLabel(THREE,`${d.size} · ${d.label}`);label.position.set(0,2,0);label.scale.set(5.4,1,1);label.userData.labDecoration=true;root.add(label)})}
function renderCatalog(){const q=document.querySelector("#name-filter").value.trim().toLowerCase(),cat=document.querySelector("#category-filter").value,size=document.querySelector("#size-filter").value,matches=catalog.filter(d=>(!q||`${d.label} ${d.type} ${d.id}`.toLowerCase().includes(q))&&(!cat||d.category===cat)&&(!size||d.size===size));document.querySelector("#catalog-list").replaceChildren(...matches.map(d=>{const card=document.createElement("article");card.className="catalog-card";card.draggable=true;card.innerHTML=`<span class=size>${d.size}</span><span><b>${d.label}</b><small>${d.type}</small></span><em>${d.category}</em>`;card.addEventListener("dragstart",e=>e.dataTransfer.setData("application/x-bluefox-cuo",d.type));return card}))}
function setPointer(x,y){const r=canvas.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,-((y-r.top)/r.height*2-1));raycaster.setFromCamera(pointer,camera)}
function rootOf(o){while(o&&!o.userData.labId)o=o.parent;return o}
function clearVisual(){if(selectionVisual){scene.remove(selectionVisual);selectionVisual=null}}
function updateVisual(){clearVisual();if(!selected||!document.querySelector("#show-hitboxes").checked)return;selectionVisual=new THREE.Box3Helper(new THREE.Box3().setFromObject(selected),0x77e8ff);scene.add(selectionVisual)}
function updatePanel(){const p=document.querySelector("#transform-window"),ok=moveMode&&selected?.userData.labOrigin==="sandbox";p.hidden=!ok;if(!ok)return;document.querySelector("#transform-object-name").textContent=selected.userData.labInstance.definition.label;document.querySelector("#position-y").value=selected.position.y.toFixed(2);p.querySelectorAll(".axis-control").forEach(r=>r.querySelector("output").textContent=`${Math.round(THREE.MathUtils.radToDeg(selected.rotation[r.dataset.axis]))}°`)}
function select(root){selected=root;document.querySelector("#focus-selected").disabled=!root;if(!root){document.querySelector("#selection-details").textContent="Sélectionnez un objet.";clearVisual();updatePanel();return}const d=root.userData.labInstance.definition;document.querySelector("#selection-details").innerHTML=`<b>${d.label}</b><br>${d.id} · ${d.category} · taille ${d.size}<br>Hauteur : ${root.position.y.toFixed(2)}`;updateVisual();updatePanel()}
function clampXZ(p){p.x=THREE.MathUtils.clamp(p.x,CENTERS.sandbox-PLATFORM.width/2+1,CENTERS.sandbox+PLATFORM.width/2-1);p.z=THREE.MathUtils.clamp(p.z,-PLATFORM.depth/2+1,PLATFORM.depth/2-1);return p}
canvas.addEventListener("dragover",e=>e.preventDefault());canvas.addEventListener("drop",e=>{e.preventDefault();const type=e.dataTransfer.getData("application/x-bluefox-cuo");setPointer(e.clientX,e.clientY);const hit=raycaster.intersectObject(sandboxPlatform,false)[0];if(hit&&library.exists(type))select(create(type,clampXZ(hit.point.clone()),"sandbox",Math.floor(Math.random()*3)))});
canvas.addEventListener("pointerdown",e=>{if(e.button===0){setPointer(e.clientX,e.clientY);const hit=raycaster.intersectObjects(roots,true).find(h=>!h.object.userData.labDecoration),root=hit&&rootOf(hit.object);if(moveMode&&root?.userData.labOrigin==="sandbox"){select(root);drag={root,y:root.position.y};canvas.setPointerCapture(e.pointerId)}else pointerDown={x:e.clientX,y:e.clientY}}if(e.button===2)canvas.classList.add("camera-drag")});
canvas.addEventListener("pointermove",e=>{if(!drag)return;setPointer(e.clientX,e.clientY);const hit=raycaster.intersectObject(sandboxPlatform,false)[0];if(hit){const p=clampXZ(hit.point.clone());drag.root.position.set(p.x,drag.y,p.z);updateVisual();updatePanel()}});
canvas.addEventListener("pointerup",e=>{if(drag){drag=null;pointerDown=null;canvas.releasePointerCapture(e.pointerId);return}if(e.button!==0||!pointerDown)return;const isClick=Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)<=5;pointerDown=null;if(!isClick)return;setPointer(e.clientX,e.clientY);const objectHit=raycaster.intersectObjects(roots,true).find(h=>!h.object.userData.labDecoration);if(objectHit)return select(rootOf(objectHit.object));const groundHit=raycaster.intersectObjects(platforms,false)[0];select(null);if(groundHit){foxTarget.copy(groundHit.point);foxTarget.y=PLATFORM.y}});canvas.addEventListener("contextmenu",e=>e.preventDefault());window.addEventListener("pointerup",()=>canvas.classList.remove("camera-drag"));
function makeFox(){const g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:0x2794d2}),b=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.75,6,12),m);b.rotation.z=Math.PI/2;b.position.y=.65;g.add(b);return g}const fox=makeFox();fox.position.set(CENTERS.sandbox,PLATFORM.y,12);scene.add(fox);const foxTarget=fox.position.clone();
function deleteSelected(){if(selected?.userData.labOrigin!=="sandbox")return;roots.splice(roots.indexOf(selected),1);BF.disposeObject(selected);select(null)}
document.querySelector("#delete-object").onclick=deleteSelected;document.querySelector("#rotate-left").onclick=()=>rotate(Math.PI/12);document.querySelector("#rotate-right").onclick=()=>rotate(-Math.PI/12);document.querySelector("#show-hitboxes").onchange=updateVisual;
function rotate(a){if(selected){selected.rotation.y+=a;updateVisual();updatePanel()}}
document.querySelectorAll(".axis-control button").forEach(b=>b.onclick=()=>{if(!selected)return;const axis=b.closest(".axis-control").dataset.axis;selected.rotation[axis]+=THREE.MathUtils.degToRad(Number(b.dataset.step));updateVisual();updatePanel()});
function changeHeight(delta){if(!selected||selected.userData.labOrigin!=="sandbox")return;selected.position.y+=delta;updateVisual();updatePanel()}
document.querySelector("#position-down").onclick=()=>changeHeight(-.25);document.querySelector("#position-up").onclick=()=>changeHeight(.25);document.querySelector("#position-y").onchange=e=>{if(selected)selected.position.y=Number(e.target.value)||0;updateVisual();updatePanel()};
document.querySelector("#place-on-ground").onclick=()=>{if(!selected)return;ground(selected);updateVisual();updatePanel()};
document.querySelector("#reset-transform").onclick=()=>{const t=selected?.userData.labInitialTransform;if(t){selected.position.copy(t.position);selected.rotation.copy(t.rotation);updateVisual();updatePanel()}};
function focus(o,min=14){if(!o)return;const box=new THREE.Box3().setFromObject(o),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dir=camera.position.clone().sub(controls.target).normalize();cameraTransition={target:center,position:center.clone().addScaledVector(dir,Math.max(min,size*2.2))}}
document.querySelector("#focus-showroom").onclick=()=>cameraTransition={target:new THREE.Vector3(CENTERS.showroom,0,0),position:new THREE.Vector3(CENTERS.showroom,64,92)};document.querySelector("#focus-sandbox").onclick=()=>cameraTransition={target:new THREE.Vector3(CENTERS.sandbox,0,0),position:new THREE.Vector3(CENTERS.sandbox,64,92)};document.querySelector("#focus-selected").onclick=()=>focus(selected);document.querySelector("#focus-fox").onclick=()=>focus(fox,16);
document.querySelector("#move-mode").onclick=e=>{moveMode=!moveMode;e.currentTarget.setAttribute("aria-pressed",moveMode);canvas.classList.toggle("move-mode",moveMode);updatePanel()};document.querySelector("#reload-cuo").onclick=()=>location.reload();
const dialog=document.querySelector("#micro-scene-dialog"),nameInput=document.querySelector("#micro-scene-name");const slug=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,"")||"SANS-NOM";nameInput.oninput=()=>document.querySelector("#micro-scene-code").textContent=`MSC-CUSTOM-${slug(nameInput.value)}`;
document.querySelector("#save-micro-scene").onclick=()=>{dialog.showModal();nameInput.focus()};document.querySelector("#micro-scene-form").onsubmit=async e=>{if(e.submitter?.value==="cancel")return;e.preventDefault();const list=roots.filter(r=>r.userData.labOrigin==="sandbox");if(!list.length){toast("Ajoutez au moins un objet sur le plateau test.");return}const center=list.reduce((s,r)=>s.add(r.position),new THREE.Vector3()).multiplyScalar(1/list.length),template={id:`MSC-CUSTOM-${slug(nameInput.value)}`,name:nameInput.value,objects:list.map(r=>({type:r.userData.labInstance.definition.type,offset:[r.position.x-center.x,r.position.y-center.y,r.position.z-center.z],variant:r.userData.labVariant||0,rotation:[r.rotation.x,r.rotation.y,r.rotation.z]}))},button=e.submitter;button.disabled=true;try{const res=await fetch("/api/custom-micro-scenes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(template)}),result=await res.json();if(!res.ok)throw new Error(result.error||"Sauvegarde refusée");document.querySelector("#micro-scene-code").textContent=result.id;dialog.close();toast(`${result.id} sauvegardée · ${result.total} scène(s) conservée(s).`)}catch(error){toast(`Échec de sauvegarde : ${error.message}`)}finally{button.disabled=false}};
const win=document.querySelector("#catalog-window");document.querySelector("#minimize-window").onclick=()=>win.classList.toggle("minimized");document.querySelector("#maximize-window").onclick=()=>win.classList.toggle("maximized");
function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/Math.max(1,canvas.clientHeight);camera.updateProjectionMatrix()}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),direction=foxTarget.clone().sub(fox.position);if(direction.lengthSq()>.0001){const step=Math.min(direction.length(),dt*4.5);fox.position.addScaledVector(direction.normalize(),step);fox.rotation.y=Math.atan2(-direction.z,direction.x)}resize();if(cameraTransition){camera.position.lerp(cameraTransition.position,.12);controls.target.lerp(cameraTransition.target,.12);if(camera.position.distanceTo(cameraTransition.position)<.04)cameraTransition=null}controls.update();renderer.render(scene,camera)}
const category=document.querySelector("#category-filter");[...new Set(catalog.map(x=>x.category))].sort().forEach(x=>category.add(new Option(x,x)));["#name-filter","#category-filter","#size-filter"].forEach(s=>document.querySelector(s).oninput=renderCatalog);renderCatalog();populate();document.querySelector("#catalog-status").textContent=`${catalog.length} objets exécutables · schéma CUO v${library.schemaVersion}${validation.valid?" · valide":""}`;animate();
